(move start-loc food-loc)
(pick-up cucumber1 food-loc)
(move food-loc chop-loc)
(place-in cucumber1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 cucumber1 chop-loc)
; (prepared slice cucumber1)
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc plate-loc)
(transfer board1 plate1 plate-loc)
; (in-receptacle cucumber1 plate1)
