(move start-loc food-loc)
(pick-up peach1 food-loc)
(move food-loc board-loc)
(place-in peach1 board1 board-loc)
(move board-loc chop-loc)
(pick-up knife1 chop-loc)
(move chop-loc board-loc)
(prepare slice board1 knife1 peach1 board-loc)
; (prepared slice peach1)
(put-down knife1 board-loc)
(take-out peach1 board1 board-loc)
(move board-loc mix-loc)
(place-in peach1 mixing-bowl1 mix-loc)
(move mix-loc food-loc)
(pick-up egg1 food-loc)
(move food-loc mix-loc)
(place-in egg1 mixing-bowl1 mix-loc)
(move mix-loc food-loc)
(pick-up flour1 food-loc)
(move food-loc mix-loc)
(place-in flour1 mixing-bowl1 mix-loc)
(combine mix mixing-bowl1 mixer1 mix-loc)
; (combined-with mix egg1 flour1) (combined-with mix flour1 peach1)
(pick-up mixing-bowl1 mix-loc)
(move mix-loc oven-loc)
(transfer mixing-bowl1 tray1 oven-loc)
(cook bake tray1 oven1 oven-loc)
; (cooked-with bake egg1 flour1) (cooked-with bake flour1 peach1)
(move oven-loc start-loc)
(put-down mixing-bowl1 start-loc)
(move start-loc oven-loc)
(pick-up tray1 oven-loc)
(move oven-loc plate-loc)
(transfer tray1 plate1 plate-loc)
; (in-receptacle egg1 plate1) (in-receptacle flour1 plate1) (in-receptacle peach1 plate1)
