(move start-loc food-loc)
(pick-up potato1 food-loc)
(move food-loc chop-loc)
(place-in potato1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 potato1 chop-loc)
; (prepared slice potato1)
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc fryer-loc)
(transfer board1 basket1 fryer-loc)
(cook deep-fry basket1 fryer1 fryer-loc)
; (cooked deep-fry potato1)
(move fryer-loc chop-loc)
(put-down board1 chop-loc)
(move chop-loc fryer-loc)
(pick-up basket1 fryer-loc)
(move fryer-loc plate-loc)
(transfer basket1 plate1 plate-loc)
; (in-receptacle potato1 plate1)
