; Baked apple pie made of sliced apples baked in dough made from egg and flour.
        (exists (?egg - food ?apple - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type apple ?apple)
                     (receptacle-type plate ?plate)
                     (prepared slice ?apple)
                     (combined-with mix ?egg ?flour)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?apple)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?flour ?plate)
                     (in-receptacle ?apple ?plate)))
; Baked peach cobbler made of sliced peaches baked in dough made from egg and flour.
        (exists (?egg - food ?peach - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type peach ?peach)
                     (receptacle-type plate ?plate)
                     (prepared slice ?peach)
                     (combined-with mix ?egg ?flour)
                     (combined-with mix ?flour ?peach)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?peach)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?flour ?plate)
                     (in-receptacle ?peach ?plate)))
; Grape jelly donut made from egg and flour dough, filled with grape jelly, and deep fried.
        (exists (?egg - food ?grape - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type grape ?grape)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?egg ?flour)
                     (cooked-with deep-fry ?egg ?flour)
                     (cooked-with deep-fry ?flour ?grape)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?grape ?plate)
                     (in-receptacle ?flour ?plate)))
; Baked chocolate cake made from chocolate, egg and flour.
        (exists (?egg - food ?chocolate - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type chocolate ?chocolate)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?egg ?flour)
                     (combined-with mix ?flour ?chocolate)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?chocolate)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?chocolate ?plate)
                     (in-receptacle ?flour ?plate)))
; Baked strawberry cake made from strawberry, egg and flour.
        (exists (?egg - food ?strawberry - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type strawberry ?strawberry)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?egg ?flour)
                     (combined-with mix ?flour ?strawberry)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?strawberry)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?strawberry ?plate)
                     (in-receptacle ?flour ?plate)))