; A California roll made from rice, crab, nori, cucumber and avocado.
        (exists (?avocado - food  ?nori - food ?rice - food ?crab - food ?cucumber - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type crab ?crab)
                     (food-type cucumber ?cucumber)
                     (food-type avocado ?avocado)
                     (receptacle-type plate ?plate)
                     (prepared slice ?crab)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?avocado ?plate)
                     (in-receptacle ?crab ?plate)))
; A tuna sushi roll made from tuna, nori, and rice.
        (exists (?nori - food ?rice - food ?tuna - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)))
; Assorted sushi rolls made from avocado, tuna, salmon, nori and rice. 
        (exists (?avocado - food  ?nori - food ?rice - food ?tuna - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (food-type salmon ?salmon)
                     (food-type avocado ?avocado)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)
                     (in-receptacle ?avocado ?plate)
                     (in-receptacle ?salmon ?plate)))
; A crab sushi roll made from crab, nori, and rice.
        (exists (?nori - food ?rice - food ?crab - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type crab ?crab)
                     (receptacle-type plate ?plate)
                     (prepared slice ?crab)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?crab ?plate)))
; An avocado sushi roll made from cucumber, avocado, nori and rice.
        (exists (?avocado - food  ?nori - food ?rice - food ?cucumber - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type cucumber ?cucumber)
                     (food-type avocado ?avocado)
                     (receptacle-type plate ?plate)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?avocado ?plate)))