(move start-loc chop-loc)
(pick-up board1 chop-loc)
(move chop-loc food-loc)
(put-down board1 food-loc)
(pick-up onion1 food-loc)
(place-in onion1 board1 food-loc)
(pick-up lettuce1 food-loc)
(place-in lettuce1 board1 food-loc)
(pick-up tomato1 food-loc)
(place-in tomato1 board1 food-loc)
(pick-up cucumber1 food-loc)
(place-in cucumber1 board1 food-loc)
; They move the onion, lettuce, tomato and cucumber chopping board.
(move food-loc chop-loc)
(pick-up knife1 chop-loc)
(move chop-loc food-loc)
(prepare slice board1 knife1 onion1 food-loc)
(prepare slice board1 knife1 lettuce1 food-loc)
(prepare slice board1 knife1 cucumber1 food-loc)
(prepare slice board1 knife1 tomato1 food-loc)
; They slice the onion, lettuce, tomato, and cucumber.
(put-down knife1 food-loc)
(pick-up board1 food-loc)
(move food-loc plate-loc)
(transfer board1 plate1 plate-loc)
; They transfer the slices onion, lettuce, tomato, and cucumber.
(move plate-loc food-loc)
(put-down board1 food-loc)
(pick-up salad-dressing1 food-loc)
(move food-loc plate-loc)
(place-in salad-dressing1 plate1 plate-loc)
; They pick up the salad dressing and add it to the place of sliced onion, lettuce, tomato, and cucumber.
