(move start-loc food-loc)
(pick-up lettuce1 food-loc)
(move food-loc chop-loc)
(place-in lettuce1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up tomato1 food-loc)
(move food-loc chop-loc)
(place-in tomato1 board1 chop-loc)
; They place lettuce and tomato on the chopping board.
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 lettuce1 chop-loc)
(prepare slice board1 knife1 tomato1 chop-loc)
; They slice lettuce and tomato on the chopping board.
(put-down knife1 chop-loc)
(move chop-loc food-loc)
(pick-up onion1 food-loc)
(move food-loc chop-loc)
(place-in onion1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 onion1 chop-loc)
; They get some onion and slice it on the chopping board.
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc plate-loc)
(transfer board1 plate1 plate-loc)
; They transfer the prepared ingredients to the plate.
