(move start-loc food-loc)
(pick-up tuna1 food-loc)
(move food-loc stove-loc)
(place-in tuna1 pan1 stove-loc)
(cook grill pan1 stove1 stove-loc)
; (cooked grill tuna1)
(pick-up pan1 stove-loc)
(move stove-loc plate-loc)
(transfer pan1 plate1 plate-loc)
; (in-receptacle tuna1 plate1)
