(move start-loc food-loc)
(pick-up flour1 food-loc)
(move food-loc mix-loc)
(place-in flour1 mixing-bowl1 mix-loc)
(move mix-loc food-loc)
(pick-up egg1 food-loc)
(move food-loc mix-loc)
(place-in egg1 mixing-bowl1 mix-loc)
(combine mix mixing-bowl1 mixer1 mix-loc)
; (combined-with mix egg1 flour1)
(move mix-loc food-loc)
(pick-up apple1 food-loc)
(move food-loc chop-loc)
(place-in apple1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 apple1 chop-loc)
; (prepared slice apple1)
(put-down knife1 chop-loc)
(take-out apple1 board1 chop-loc)
(move chop-loc mix-loc)
(place-in apple1 mixing-bowl1 mix-loc)
(pick-up mixing-bowl1 mix-loc)
(move mix-loc fryer-loc)
(transfer mixing-bowl1 basket1 fryer-loc)
(cook deep-fry basket1 fryer1 fryer-loc)
; (cooked-with deep-fry egg1 flour1) (cooked-with deep-fry flour1 apple1)
(move fryer-loc plate-loc)
(put-down mixing-bowl1 plate-loc)
(move plate-loc fryer-loc)
(pick-up basket1 fryer-loc)
(move fryer-loc plate-loc)
(transfer basket1 plate1 plate-loc)
; (in-receptacle egg1 plate1) (in-receptacle apple1 plate1) (in-receptacle flour1 plate1)
