(move start-loc food-loc)
(pick-up lettuce1 food-loc)
(move food-loc chop-loc)
(place-in lettuce1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up onion1 food-loc)
(move food-loc chop-loc)
(place-in onion1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up tomato1 food-loc)
(move food-loc chop-loc)
(place-in tomato1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up ham1 food-loc)
(move food-loc chop-loc)
(place-in ham1 board1 chop-loc)
; Place lettuce, onion, tomato, and ham on the chopping board.
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 lettuce1 chop-loc)
(prepare slice board1 knife1 tomato1 chop-loc)
(prepare slice board1 knife1 onion1 chop-loc)
(prepare slice board1 knife1 ham1 chop-loc)
; Slice the lettuce, tomato, onion and ham.
(put-down knife1 chop-loc)
(move chop-loc food-loc)
(pick-up bread1 food-loc)
(move food-loc plate-loc)
(place-in bread1 plate1 plate-loc)
; Place some bread on a plate.
(move plate-loc food-loc)
(pick-up bacon1 food-loc)
(move food-loc stove-loc)
(place-in bacon1 pan1 stove-loc)
(cook grill pan1 stove1 stove-loc)
; Find some bacon and grill it on the stove.
(pick-up pan1 stove-loc)
(move stove-loc plate-loc)
(transfer pan1 plate1 plate-loc)
; Transfer the grilled bacon to the plate.
(put-down pan1 plate-loc)
(move plate-loc chop-loc)
(pick-up board1 chop-loc)
(move chop-loc plate-loc)
(transfer board1 plate1 plate-loc)
; Transfer the ham and vegetables from the chopping board to the plate.
(put-down board1 plate-loc)
(move plate-loc food-loc)
(pick-up mayo1 food-loc)
(move food-loc plate-loc)
(place-in mayo1 plate1 plate-loc)
; Pick up some mayo and add it to the plate.
