(move start-loc food-loc)
(pick-up egg1 food-loc)
(move food-loc mix-loc)
(place-in egg1 mixing-bowl1 mix-loc)
(move mix-loc food-loc)
(pick-up flour1 food-loc)
(move food-loc mix-loc)
(place-in flour1 mixing-bowl1 mix-loc)
(combine mix mixing-bowl1 mixer1 mix-loc)
; Mix the flour and egg in the mixing bowl to become a dough.
(pick-up mixing-bowl1 mix-loc)
(move mix-loc tray-loc)
(transfer mixing-bowl1 tray1 tray-loc)
(put-down mixing-bowl1 tray-loc)
; Transfer the egg-and-flour dough to the tray.
(move tray-loc chop-loc)
(pick-up board1 chop-loc)
(move chop-loc food-loc)
(put-down board1 food-loc)
(pick-up mushroom1 food-loc)
(place-in mushroom1 board1 food-loc)
; Pick up the chopping board, place it next to the food, then place mushroom on the chopping board.
(pick-up onion1 food-loc)
(place-in onion1 board1 food-loc)
(pick-up olive1 food-loc)
(place-in olive1 board1 food-loc)
(move food-loc chop-loc)
(pick-up knife1 chop-loc)
(move chop-loc food-loc)
(prepare slice board1 knife1 onion1 food-loc)
(prepare slice board1 knife1 olive1 food-loc)
(prepare slice board1 knife1 mushroom1 food-loc)
; Add onion and olive to the chopping board, then slice the onion, olive, and mushroom.
(put-down knife1 food-loc)
(pick-up tomato1 food-loc)
(place-in tomato1 board1 food-loc)
(pick-up knife1 food-loc)
(prepare slice board1 knife1 tomato1 food-loc)
; Place tomato on the chopping board and slice the tomato.
(put-down knife1 food-loc)
(pick-up board1 food-loc)
(move food-loc tray-loc)
(transfer board1 tray1 tray-loc)
(put-down board1 tray-loc)
; Transfer everything on the chopping board into the tray.
(move tray-loc food-loc)
(pick-up cheese1 food-loc)
(move food-loc tray-loc)
(place-in cheese1 tray1 tray-loc)
(pick-up tray1 tray-loc)
(move tray-loc oven-loc)
(put-down tray1 oven-loc)
(cook bake tray1 oven1 oven-loc)
; Add cheese to the tray, then bake the tray in the oven.
(pick-up tray1 oven-loc)
(move oven-loc plate-loc)
(transfer tray1 plate1 plate-loc)
; Transfer the baked food in the tray to the plate.
