(move start-loc food-loc)
(pick-up mushroom1 food-loc)
(move food-loc chop-loc)
(place-in mushroom1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up onion1 food-loc)
(move food-loc chop-loc)
(place-in onion1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up olive1 food-loc)
(move food-loc chop-loc)
(place-in olive1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 onion1 chop-loc)
(prepare slice board1 knife1 olive1 chop-loc)
(prepare slice board1 knife1 mushroom1 chop-loc)
; They pick up mushroom, onion, and olive, then slice them on the chopping board.
(put-down knife1 chop-loc)
(move chop-loc food-loc)
(pick-up flour1 food-loc)
(move food-loc mix-loc)
(place-in flour1 mixing-bowl1 mix-loc)
(move mix-loc food-loc)
(pick-up egg1 food-loc)
(move food-loc mix-loc)
(place-in egg1 mixing-bowl1 mix-loc)
(combine mix mixing-bowl1 mixer1 mix-loc)
; They combine egg and flour in the mixing bowl using the mixer.
(pick-up mixing-bowl1 mix-loc)
(move mix-loc tray-loc)
(transfer mixing-bowl1 tray1 tray-loc)
(put-down mixing-bowl1 tray-loc)
; They transfer the contents of the mixing bowl to the tray.
(move tray-loc chop-loc)
(pick-up board1 chop-loc)
(move chop-loc tray-loc)
(transfer board1 tray1 tray-loc)
(put-down board1 tray-loc)
; They transfer the vegetables on the chopping board to the tray.
(move tray-loc food-loc)
(pick-up cheese1 food-loc)
(move food-loc tray-loc)
(place-in cheese1 tray1 tray-loc)
(pick-up tray1 tray-loc)
(move tray-loc oven-loc)
(put-down tray1 oven-loc)
(cook bake tray1 oven1 oven-loc)
; They add cheese to the tray, then bake the tray in the oven.
(pick-up tray1 oven-loc)
(move oven-loc plate-loc)
(transfer tray1 plate1 plate-loc)
; They transfer everything in the tray to the plate.
