(define (problem ai2thor-2d-problem)
  (:domain ai2thor-2d)
  (:objects cylinder1 - cylinder block1 - block)
  (:init (= (width) (10))
         (= (height) (10))
         (= (xpos) (5))
         (= (ypos) (5))
         (handsfree)
         (wall 1 1)
         (wall 2 1)
         (wall 3 1)
         (wall 4 1)
         (wall 5 1)
         (wall 6 1)
         (wall 7 1)
         (wall 8 1)
         (wall 9 1)
         (wall 10 1)
         (wall 1 2)
         (wall 3 2)
         (wall 7 2)
         (wall 10 2)
         (wall 1 3)
         (wall 4 3)
         (wall 7 3)
         (wall 9 3)
         (wall 10 3)
         (wall 1 4)
         (= (xitem block1) (2))
         (= (yitem block1) (4))
         (wall 4 4)
         (wall 9 4)
         (wall 10 4)
         (wall 1 5)
         (wall 10 5)
         (wall 1 6)
         (wall 4 6)
         (wall 7 6)
         (wall 8 6)
         (wall 10 6)
         (wall 1 7)
         (wall 7 7)
         (wall 9 7)
         (wall 10 7)
         (wall 1 8)
         (= (xitem cylinder1) (2))
         (= (yitem cylinder1) (8))
         (wall 5 8)
         (wall 10 8)
         (wall 1 9)
         (wall 5 9)
         (wall 8 9)
         (wall 10 9)
         (wall 1 10)
         (wall 2 10)
         (wall 3 10)
         (wall 4 10)
         (wall 5 10)
         (wall 6 10)
         (wall 7 10)
         (wall 8 10)
         (wall 9 10)
         (wall 10 10))
  (:goal (retrieve cylinder1))
)
