;; ASCII ;;
; W: wall, F: furniture, c: cylinder, b: block, s: start, .: empty
; ................
; ...s............
; ..WWWWW.........
; ................
; ................
; ................
; ......FFFFF.....
; ......FFFFF.....
; ................
; ................
; ................
; ...W............
; ...W............
; ...W..c.........
; ...W............
; ...W............
(define (problem ai2thor-2d-problem)
  (:domain ai2thor-2d)
  (:objects cylinder1 - cylinder)
  (:init (= (width) (16))
         (= (height) (16))
         (= (xpos) (4))
         (= (ypos) (15))
         (handsfree)
         (wall 4 1)
         (wall 4 2)
         (wall 4 3)
         (= (xitem cylinder1) (7))
         (= (yitem cylinder1) (3))
         (wall 4 4)
         (wall 4 5)
         (furniture 7 9)
         (furniture 8 9)
         (furniture 9 9)
         (furniture 10 9)
         (furniture 11 9)
         (furniture 7 10)
         (furniture 8 10)
         (furniture 9 10)
         (furniture 10 10)
         (furniture 11 10)
         (wall 3 14)
         (wall 4 14)
         (wall 5 14)
         (wall 6 14)
         (wall 7 14))
  (:goal (transfer cylinder1 7 8))
)
