(define (problem blocks-1)
  (:domain blocks)
  (:objects
    table - block
    block1 - block)
  (:init
    (on table block1)
    (= (size table) 16)
    (= (size block1) 3)
    (= (amounton table) 3)
    (= (amounton block1) 0)
    (= (posx table) 3)
    (= (posy table) 3)
    (= (posz table) -8)
    (= (yaw table) 0)
    (= (pitch table) 0)
    (= (roll table) 0)
    (= (posx block1) 0)
    (= (posy block1) 0)
    (= (posz block1) -1)
    (= (yaw block1) 0)
    (= (pitch block1) -1)
    (= (roll block1) -1))
  (:goal (holding block1)))
