(move start-loc food-loc)
(pick-up flour1 food-loc)
(move food-loc mix-loc)
(place-in flour1 mixing-bowl1 mix-loc)
(move mix-loc food-loc)
(pick-up egg1 food-loc)
(move food-loc mix-loc)
(place-in egg1 mixing-bowl1 mix-loc)
(combine mix mixing-bowl1 mixer1 mix-loc)
; (combined-with mix egg1 flour1)
(pick-up mixing-bowl1 mix-loc)
(move mix-loc tray-loc)
(transfer mixing-bowl1 tray1 tray-loc)
(put-down mixing-bowl1 tray-loc)
(pick-up tray1 tray-loc)
(move tray-loc food-loc)
(put-down tray1 food-loc)
(pick-up cheese1 food-loc)
(place-in cheese1 tray1 food-loc)
(pick-up tray1 food-loc)
(move food-loc oven-loc)
(put-down tray1 oven-loc)
(cook bake tray1 oven1 oven-loc)
; (cooked-with bake egg1 flour1) (cooked-with bake flour1 cheese1)
(pick-up tray1 oven-loc)
(move oven-loc plate-loc)
(transfer tray1 plate1 plate-loc)
; (in-receptacle cheese1 plate1) (in-receptacle egg1 plate1) (in-receptacle flour1 plate1)
