(move start-loc food-loc)
(pick-up orange1 food-loc)
(move food-loc chop-loc)
(place-in orange1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up peach1 food-loc)
(move food-loc chop-loc)
(place-in peach1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 peach1 chop-loc)
(prepare slice board1 knife1 orange1 chop-loc)
; (prepared slice orange1) (prepared slice peach1)
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc glass-loc)
(transfer board1 glass1 glass-loc)
; (in-receptacle orange1 glass1) (in-receptacle peach1 glass1)
(move glass-loc food-loc)
(put-down board1 food-loc)
(pick-up grape1 food-loc)
(move food-loc glass-loc)
(place-in grape1 glass1 glass-loc)
; (in-receptacle grape1 glass1)
