(move start-loc food-loc)
(pick-up apple1 food-loc)
(move food-loc chop-loc)
(place-in apple1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 apple1 chop-loc)
; (prepared slice apple1)
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc plate-loc)
(transfer board1 plate1 plate-loc)
; (in-receptacle apple1 plate1)
