(move start-loc food-loc)
(pick-up apple1 food-loc)
(move food-loc chop-loc)
(place-in apple1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up strawberry1 food-loc)
(move food-loc chop-loc)
(place-in strawberry1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 strawberry1 chop-loc)
(prepare slice board1 knife1 apple1 chop-loc)
; (prepared slice apple1) (prepared slice strawberry1)
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc glass-loc)
(transfer board1 glass1 glass-loc)
; (in-receptacle apple1 glass1) (in-receptacle strawberry1 glass1)
(move glass-loc food-loc)
(put-down board1 food-loc)
(pick-up grape1 food-loc)
(move food-loc glass-loc)
(place-in grape1 glass1 glass-loc)
; (in-receptacle grape1 glass1)
