(move start-loc food-loc)
(pick-up avocado1 food-loc)
(move food-loc chop-loc)
(place-in avocado1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 avocado1 chop-loc)
; (prepared slice avocado1)
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc plate-loc)
(transfer board1 plate1 plate-loc)
; (in-receptacle avocado1 plate1)
