; Goal 1: Mushroom pizza
        (exists (?egg - food ?flour - food ?tomato - food ?cheese - food ?mushroom - food ?plate - receptacle)
            (and (food-type egg ?egg)
                 (food-type flour ?flour)
                 (food-type tomato ?tomato)
                 (food-type cheese ?cheese)
                 (food-type mushroom ?mushroom)
                 (receptacle-type plate ?plate)
                 (prepared slice ?mushroom)
                 (prepared slice ?tomato)
                 (combined-with mix ?egg ?flour)
                 (cooked-with bake ?egg ?flour)
                 (cooked-with bake ?tomato ?flour)
                 (cooked-with bake ?tomato ?cheese)
                 (cooked-with bake ?cheese ?mushroom)
                 (in-receptacle ?tomato ?plate)
                 (in-receptacle ?cheese ?plate)
                 (in-receptacle ?mushroom ?plate)
                 (in-receptacle ?egg ?plate)
                 (in-receptacle ?flour ?plate)))
; Goal 2: Onion pizza
        (exists (?egg - food ?flour - food ?tomato - food ?cheese - food ?onion - food ?plate - receptacle)
            (and (food-type egg ?egg)
                 (food-type flour ?flour)
                 (food-type tomato ?tomato)
                 (food-type cheese ?cheese)
                 (food-type onion ?onion)
                 (receptacle-type plate ?plate)
                 (prepared slice ?onion)
                 (prepared slice ?tomato)
                 (combined-with mix ?egg ?flour)
                 (cooked-with bake ?egg ?flour)
                 (cooked-with bake ?tomato ?flour)
                 (cooked-with bake ?tomato ?cheese)
                 (cooked-with bake ?cheese ?onion)
                 (in-receptacle ?tomato ?plate)
                 (in-receptacle ?cheese ?plate)
                 (in-receptacle ?onion ?plate)
                 (in-receptacle ?egg ?plate)
                 (in-receptacle ?flour ?plate)))
; Goal 3: Olive pizza
        (exists (?egg - food ?flour - food ?tomato - food ?cheese - food ?olive - food ?plate - receptacle)
            (and (food-type egg ?egg)
                 (food-type flour ?flour)
                 (food-type tomato ?tomato)
                 (food-type cheese ?cheese)
                 (food-type olive ?olive)
                 (receptacle-type plate ?plate)
                 (prepared slice ?olive)
                 (prepared slice ?tomato)
                 (combined-with mix ?egg ?flour)
                 (cooked-with bake ?egg ?flour)
                 (cooked-with bake ?tomato ?flour)
                 (cooked-with bake ?tomato ?cheese)
                 (cooked-with bake ?cheese ?olive)
                 (in-receptacle ?tomato ?plate)
                 (in-receptacle ?cheese ?plate)
                 (in-receptacle ?olive ?plate)
                 (in-receptacle ?egg ?plate)
                 (in-receptacle ?flour ?plate)))
; Goal 4: Veggie pizza (all veggies)
        (exists (?egg - food ?flour - food ?tomato - food ?cheese - food ?onion - food ?mushroom - food ?olive - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type cheese ?cheese)
                     (food-type onion ?onion)
                     (food-type mushroom ?mushroom)
                     (food-type olive ?olive)
                     (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?onion)
                     (prepared slice ?mushroom)
                     (prepared slice ?olive)
                     (prepared slice ?tomato)
                     (combined-with mix ?egg ?flour)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?cheese)
                     (cooked-with bake ?cheese ?olive)
                     (cooked-with bake ?olive ?mushroom)
                     (cooked-with bake ?mushroom ?onion)
                     (cooked-with bake ?onion ?tomato)
                     (in-receptacle ?cheese ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?mushroom ?plate)
                     (in-receptacle ?olive ?plate)
                     (in-receptacle ?onion ?plate)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?flour ?plate)))
; Goal 5: Veggie calzone
        (exists (?egg - food ?flour - food ?cheese - food ?onion - food ?mushroom - food ?olive - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type cheese ?cheese)
                     (food-type onion ?onion)
                     (food-type mushroom ?mushroom)
                     (food-type olive ?olive)
                     (receptacle-type plate ?plate)
                     (prepared slice ?onion)
                     (prepared slice ?mushroom)
                     (prepared slice ?olive)
                     (combined-with mix ?egg ?flour)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?cheese)
                     (cooked-with bake ?cheese ?olive)
                     (cooked-with bake ?olive ?mushroom)
                     (cooked-with bake ?mushroom ?onion)
                     (in-receptacle ?cheese ?plate)
                     (in-receptacle ?mushroom ?plate)
                     (in-receptacle ?olive ?plate)
                     (in-receptacle ?onion ?plate)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?flour ?plate)))