;Goal 1: Salmon, nori, rice
    (exists (?nori - food ?rice - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?salmon ?plate)))
    
; Goal 2: Tuna, nori, rice
        (exists (?nori - food ?rice - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?salmon ?plate)))
; Goal 3: Tuna, salmon, nori, rice
        (exists (?nori - food ?rice - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?salmon ?plate)))
; Goal 4: tuna rice
        (exists (?nori - food ?rice - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?salmon ?plate)))
; Goal 5: salmon rice
        (exists (?nori - food ?rice - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?salmon ?plate)))