; Goal 1: Grilled chicken sandwich
        (exists (?bread - food ?chicken - food ?cheese - food ?lettuce - food ?tomato - food ?plate - receptacle)
            (and (food-type chicken ?chicken)
                 (food-type bread ?bread)
                 (food-type cheese ?cheese)
                 (food-type lettuce ?lettuce)
                 (food-type tomato ?tomato)
                 (receptacle-type plate ?plate)
                 (prepared slice ?cheese)
                 (prepared slice ?tomato)
                 (prepared slice ?lettuce)
                 (cooked grill ?chicken)
                 (in-receptacle ?chicken ?plate)
                 (in-receptacle ?bread ?plate)
                 (in-receptacle ?lettuce ?plate)
                 (in-receptacle ?tomato ?plate)
                 (in-receptacle ?cheese ?plate)))
; Goal 2: Cheesburger
        (exists (?hamburger-bun - food ?beef - food ?cheese - food ?plate - receptacle)
                (and (food-type beef ?beef)
                     (food-type hamburger-bun ?hamburger-bun)
                     (food-type cheese ?cheese)
                     (receptacle-type plate ?plate)
                     (cooked grill ?beef)
                     (prepared slice ?cheese)
                     (in-receptacle ?hamburger-bun ?plate)
                     (in-receptacle ?beef ?plate)
                     (in-receptacle ?cheese ?plate)))    
; Goal 3: Fried Chicken
        (exists (?chicken - food ?plate - receptacle)
                (and (food-type chicken ?chicken)
                     (receptacle-type plate ?plate)
                     (prepared slice ?chicken)
                     (cooked deep-fry ?chicken)
                     (in-receptacle ?chicken ?plate)))
; Goal 4: Fried Chicken and fries
        (exists (?potato - food ?chicken - food ?plate - receptacle)
                (and (food-type potato ?potato)
                     (food-type chicken ?chicken)
                     (receptacle-type plate ?plate)
                     (prepared slice ?potato)
                     (prepared slice ?chicken)
                     (cooked deep-fry ?potato)
                     (cooked deep-fry ?chicken)
                     (in-receptacle ?chicken ?plate)
                     (in-receptacle ?potato ?plate)))
; Goal 5: Hamburger and grilled chicken sandwich
        (exists (?bread - food ?bacon - food ?lettuce - food ?tomato - food ?mayonnaise - food ?plate - receptacle)
                (and (food-type bacon ?bacon)
                     (food-type bread ?bread)
                     (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type mayonnaise ?mayonnaise)
                     (receptacle-type plate ?plate)
                     (cooked grill ?bacon)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?bacon ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?mayonnaise ?plate)
                     (in-receptacle ?lettuce ?plate)))