;Goal 1: Tuna roll
        (exists (?nori - food ?rice - food ?tuna - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)))
;Goal 2: Tuna salmon avocado roll
        (exists (?avocado - food  ?nori - food ?rice - food ?tuna - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (food-type salmon ?salmon)
                     (food-type avocado ?avocado)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)
                     (in-receptacle ?avocado ?plate)
                     (in-receptacle ?salmon ?plate)))
;Goal 3: Edamame
    (exists (?soybean - food ?plate - receptacle)
            (and (food-type soybean ?soybean)
                 (cooked boil ?soybean)
                 (in-receptacle ?plate)))
;Goal 4: Cucumber Avocado roll
        (exists (?avocado - food  ?nori - food ?rice - food ?cucumber - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type cucumber ?cucumber)
                     (food-type avocado ?avocado)
                     (receptacle-type plate ?plate)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?avocado ?plate)))
;Goal 5: California Roll
        (exists (?avocado - food  ?nori - food ?rice - food ?crab - food ?cucumber - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type crab ?crab)
                     (food-type cucumber ?cucumber)
                     (food-type avocado ?avocado)
                     (receptacle-type plate ?plate)
                     (prepared slice ?crab)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?avocado ?plate)
                     (in-receptacle ?crab ?plate)))