;Goal 1: Tuna cucumber roll
        (exists (?nori - food ?rice - food ?tuna - food ?cucumber - food  ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (food-type cucumber ?cucumber)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (prepared slice ?cucumber)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?tuna ?plate)))
; Goal 2: Salmon cucumber roll
        (exists (?nori - food ?rice - food ?cucumber - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type cucumber ?cucumber)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?salmon)
                     (prepared slice ?cucumber)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?cucumber ?plate)))
; Goal 3: Cucumber roll
        (exists (?nori - food ?rice - food ?cucumber - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type cucumber ?cucumber)
                     (receptacle-type plate ?plate)
                     (prepared slice ?cucumber)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?cucumber ?plate)))
; Goal 4: Tuna, salmon, cucumber
        (exists (?nori - food ?rice - food ?tuna - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?salmon ?plate)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)))
; Goal 5: Tuna nori roll
        (exists (?nori - food ?rice - food ?tuna - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)))