;Goal 1: Grilled Cheese
        (exists (?bread - food ?cheese - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type cheese ?cheese)
                     (receptacle-type plate ?plate)
                     (prepared slice ?cheese)
                     (cooked-with grill ?bread ?cheese)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?cheese ?plate)))
;Goal 2: Ham and cheese
        (exists (?ham - food ?bread - food ?cheese - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type ham ?ham)
                     (food-type cheese ?cheese)
                     (receptacle-type plate ?plate)
                     (prepared slice ?ham)
                     (prepared slice ?cheese)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?cheese ?plate)))
;Goal 3: Ham x LT
        (exists (?ham - food ?bread - food ?cheese - food ?lettuce - food ?tomato - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type ham ?ham)
                     (food-type cheese ?cheese)
                     (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?ham)
                     (prepared slice ?cheese)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?cheese ?plate)))
;Goal 4: Ham or Cheese x LTO
        (exists (?ham - food ?bread - food ?cheese - food ?lettuce - food ?tomato - food ?onion - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type ham ?ham)
                     (food-type cheese ?cheese)
                     (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type onion ?onion)
                     (receptacle-type plate ?plate)
                     (prepared slice ?ham)
                     (prepared slice ?cheese)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (prepared slice ?onion)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?onion ?plate)
                     (in-receptacle ?cheese ?plate)))
;Goal 5: Grilled ham and cheese
        (exists (?ham - food ?bread - food ?cheese - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type ham ?ham)
                     (food-type cheese ?cheese)
                     (receptacle-type plate ?plate)
                     (prepared slice ?ham)
                     (prepared slice ?cheese)
                     (cooked-with grill ?bread ?cheese)
                     (cooked-with grill ?ham ?cheese)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?cheese ?plate)))