
;Goal 1: Sliced tomato
        (exists (?tomato - food ?knife - tool ?plate - receptacle)
                (and (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tomato)
                     (in-receptacle ?tomato ?plate)))
;Goal 2: Sliced lettuce
        (exists (?lettuce - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (in-receptacle ?lettuce ?plate)))
;Goal 3: Sliced lettuce, tomato, cucumber, salad dressing
        (exists (?lettuce - food ?tomato - food ?cucumber - food ?salad-dressing - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type cucumber ?cucumber)
                     (food-type salad-dressing ?salad-dressing)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (prepared slice ?cucumber)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?salad-dressing ?plate)))
;Goal 4: Sliced lettuce, tomato, onion, salad dressing
        (exists (?lettuce - food ?tomato - food ?onion - food ?salad-dressing - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type onion ?onion)
                     (food-type salad-dressing ?salad-dressing)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (prepared slice ?onion)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?onion ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?salad-dressing ?plate)))
;Goal 5: Sliced lettuce, tomato, onion, cucumber, salad dressing
        (exists (?lettuce - food ?tomato - food ?cucumber - food ?onion - food ?salad-dressing - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type cucumber ?cucumber)
                     (food-type onion ?onion)
                     (food-type salad-dressing ?salad-dressing)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (prepared slice ?cucumber)
                     (prepared slice ?onion)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?onion ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?salad-dressing ?plate)))