; Goal 1: Tuna sandwich
        (exists (?bread - food ?tuna - food ?cheese - food ?lettuce - food ?tomato - food ?mayonnaise - food ?plate - receptacle ?mixing-bowl - receptacle)
            (and (food-type tuna ?tuna)
                 (food-type bread ?bread)
                 (food-type cheese ?cheese)
                 (food-type lettuce ?lettuce)
                 (food-type tomato ?tomato)
                 (food-type mayonnaise ?mayonnaise)
                 (receptacle-type plate ?plate)
                 (combined-with mix ?tuna ?mayonnaise)
                 (prepared slice ?cheese)
                 (prepared slice ?tomato)
                 (prepared slice ?lettuce)
                 (in-receptacle ?bread ?plate)
                 (in-receptacle ?tuna ?plate)
                 (in-receptacle ?lettuce ?plate)
                 (in-receptacle ?tomato ?plate)
                 (in-receptacle ?mayonnaise ?plate)
                 (in-receptacle ?cheese ?plate)))
; Goal 2: Tuna melt
        (exists (?bread - food ?tuna - food ?cheese - food ?mayonnaise - food ?plate - receptacle ?mixing-bowl - receptacle)
            (and (food-type tuna ?tuna)
                 (food-type bread ?bread)
                 (food-type cheese ?cheese)
                 (food-type mayonnaise ?mayonnaise)
                 (receptacle-type plate ?plate)
                 (combined-with mix ?tuna ?mayonnaise)
                 (prepared slice ?cheese)
                 (cooked-with grill ?bread ?cheese)
                 (cooked-with grill ?tuna ?cheese)
                 (in-receptacle ?bread ?plate)
                 (in-receptacle ?tuna ?plate)
                 (in-receptacle ?mayonnaise ?plate)
                 (in-receptacle ?cheese ?plate)))
; Goal 3: Fries
        (exists (?potato - food ?plate - receptacle)
                (and (food-type potato ?potato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?potato)
                     (cooked deep-fry ?potato)
                     (in-receptacle ?potato ?plate)))
; Goal 4: Tuna sand + fries
        (exists (?bread - food ?tuna - food ?potato - food ?cheese - food ?lettuce - food ?tomato - food ?mayonnaise - food ?plate - receptacle ?mixing-bowl - receptacle)
            (and (food-type tuna ?tuna)
                 (food-type bread ?bread)
                 (food-type cheese ?cheese)
                 (food-type lettuce ?lettuce)
                 (food-type tomato ?tomato)
                 (food-type mayonnaise ?mayonnaise)
                 (food-type potato ?potato)
                 (receptacle-type plate ?plate)
                 (combined-with mix ?tuna ?mayonnaise)
                 (prepared slice ?cheese)
                 (prepared slice ?tomato)
                 (prepared slice ?lettuce)
                 (prepared slice ?potato)
                 (cooked deep-fry ?potato)
                 (in-receptacle ?bread ?plate)
                 (in-receptacle ?tuna ?plate)
                 (in-receptacle ?lettuce ?plate)
                 (in-receptacle ?tomato ?plate)
                 (in-receptacle ?mayonnaise ?plate)
                 (in-receptacle ?cheese ?plate)
                 (in-receptacle ?potato ?plate)))
; Goal 5: Tuna melt + fries
        (exists (?bread - food ?tuna - food ?potato - food ?cheese - food ?mayonnaise - food ?plate - receptacle ?mixing-bowl - receptacle)
            (and (food-type tuna ?tuna)
                 (food-type bread ?bread)
                 (food-type cheese ?cheese)
                 (food-type mayonnaise ?mayonnaise)
                 (food-type potato ?potato)
                 (receptacle-type plate ?plate)
                 (combined-with mix ?tuna ?mayonnaise)
                 (prepared slice ?cheese)
                 (prepared slice ?potato)
                 (cooked deep-fry ?potato)
                 (cooked-with grill ?bread ?cheese)
                 (cooked-with grill ?tuna ?cheese)
                 (in-receptacle ?bread ?plate)
                 (in-receptacle ?tuna ?plate)
                 (in-receptacle ?mayonnaise ?plate)
                 (in-receptacle ?cheese ?plate)
                 (in-receptacle ?potato ?plate)))