; Goal 1 Chocolate cake
        (exists (?egg - food ?chocolate - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type chocolate ?chocolate)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?egg ?flour)
                     (combined-with mix ?flour ?chocolate)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?chocolate)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?chocolate ?plate)
                     (in-receptacle ?flour ?plate)))
; Goal 2: Strawberry cake
        (exists (?egg - food ?strawberry - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type strawberry ?strawberry)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?egg ?flour)
                     (combined-with mix ?flour ?strawberry)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?strawberry)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?strawberry ?plate)
                     (in-receptacle ?flour ?plate)))
; Goal 3: Apple pie
        (exists (?egg - food ?apple - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type apple ?apple)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?egg ?flour)
                     (combined-with mix ?flour ?apple)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?apple)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?apple ?plate)
                     (in-receptacle ?flour ?plate)))
; Goal 4: Chocolate Strawberry cake
        (exists (?egg - food ?chocolate - food ?strawberry - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type chocolate ?chocolate)
                     (food-type strawberry ?strawberry)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?egg ?flour)
                     (combined-with mix ?flour ?strawberry)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?strawberry)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?strawberry ?plate)
                     (in-receptacle ?flour ?plate)))
; Goal 5: Chocolate strawberry
        (exists (?chocolate - food ?strawberry - food ?plate - receptacle)
                (and (food-type chocolate ?chocolate)
                     (food-type strawberry ?strawberry)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?chocolate ?strawberry)
                     (in-receptacle ?chocolate ?plate)
                     (in-receptacle ?strawberry ?plate)))