; A tuna salad sandwich made of tuna mixed with mayo, layered in bread with tomato, lettuce, and cheese.
        (exists (?bread - food ?tuna - food ?cheese - food ?lettuce - food ?tomato - food ?mayonnaise - food ?plate - receptacle ?mixing-bowl - receptacle)
            (and (food-type tuna ?tuna)
                 (food-type bread ?bread)
                 (food-type cheese ?cheese)
                 (food-type lettuce ?lettuce)
                 (food-type tomato ?tomato)
                 (food-type mayonnaise ?mayonnaise)
                 (receptacle-type plate ?plate)
                 (combined-with mix ?tuna ?mayonnaise)
                 (prepared slice ?cheese)
                 (prepared slice ?tomato)
                 (prepared slice ?lettuce)
                 (in-receptacle ?bread ?plate)
                 (in-receptacle ?tuna ?plate)
                 (in-receptacle ?lettuce ?plate)
                 (in-receptacle ?tomato ?plate)
                 (in-receptacle ?mayonnaise ?plate)
                 (in-receptacle ?cheese ?plate)))
; A tuna melt sandwich made of tuna mixed with mayo, layered in bread and grilled with cheese.
        (exists (?bread - food ?tuna - food ?cheese - food ?mayonnaise - food ?plate - receptacle ?mixing-bowl - receptacle)
            (and (food-type tuna ?tuna)
                 (food-type bread ?bread)
                 (food-type cheese ?cheese)
                 (food-type mayonnaise ?mayonnaise)
                 (receptacle-type plate ?plate)
                 (combined-with mix ?tuna ?mayonnaise)
                 (prepared slice ?cheese)
                 (cooked-with grill ?bread ?cheese)
                 (cooked-with grill ?tuna ?cheese)
                 (in-receptacle ?bread ?plate)
                 (in-receptacle ?tuna ?plate)
                 (in-receptacle ?mayonnaise ?plate)
                 (in-receptacle ?cheese ?plate)))
; A side of fries.
        (exists (?potato - food ?plate - receptacle)
                (and (food-type potato ?potato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?potato)
                     (cooked deep-fry ?potato)
                     (in-receptacle ?potato ?plate)))
; A tuna salad sandwich made of tuna mixed with mayo, layered in bread with tomato, lettuce, cheese, served with a side of fries.
        (exists (?bread - food ?tuna - food ?potato - food ?cheese - food ?lettuce - food ?tomato - food ?mayonnaise - food ?plate - receptacle ?mixing-bowl - receptacle)
            (and (food-type tuna ?tuna)
                 (food-type bread ?bread)
                 (food-type cheese ?cheese)
                 (food-type lettuce ?lettuce)
                 (food-type tomato ?tomato)
                 (food-type mayonnaise ?mayonnaise)
                 (food-type potato ?potato)
                 (receptacle-type plate ?plate)
                 (combined-with mix ?tuna ?mayonnaise)
                 (prepared slice ?cheese)
                 (prepared slice ?tomato)
                 (prepared slice ?lettuce)
                 (prepared slice ?potato)
                 (cooked deep-fry ?potato)
                 (in-receptacle ?bread ?plate)
                 (in-receptacle ?tuna ?plate)
                 (in-receptacle ?lettuce ?plate)
                 (in-receptacle ?tomato ?plate)
                 (in-receptacle ?mayonnaise ?plate)
                 (in-receptacle ?cheese ?plate)
                 (in-receptacle ?potato ?plate)))
; A tuna melt sandwich made of tuna mixed with mayo, layered in bread and grilled with cheese, served with a side of fries.
        (exists (?bread - food ?tuna - food ?potato - food ?cheese - food ?mayonnaise - food ?plate - receptacle ?mixing-bowl - receptacle)
            (and (food-type tuna ?tuna)
                 (food-type bread ?bread)
                 (food-type cheese ?cheese)
                 (food-type mayonnaise ?mayonnaise)
                 (food-type potato ?potato)
                 (receptacle-type plate ?plate)
                 (combined-with mix ?tuna ?mayonnaise)
                 (prepared slice ?cheese)
                 (prepared slice ?potato)
                 (cooked deep-fry ?potato)
                 (cooked-with grill ?bread ?cheese)
                 (cooked-with grill ?tuna ?cheese)
                 (in-receptacle ?bread ?plate)
                 (in-receptacle ?tuna ?plate)
                 (in-receptacle ?mayonnaise ?plate)
                 (in-receptacle ?cheese ?plate)
                 (in-receptacle ?potato ?plate)))