(move start-loc food-loc)
(pick-up lettuce1 food-loc)
(move food-loc chop-loc)
(place-in lettuce1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up tomato1 food-loc)
(move food-loc chop-loc)
(place-in tomato1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 tomato1 chop-loc)
(prepare slice board1 knife1 lettuce1 chop-loc)
; They pick up lettuce and tomato, then slice them on the chopping board.
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc plate-loc)
(transfer board1 plate1 plate-loc)
; They transfer the sliced lettuce and tomato to a plate.
(move plate-loc food-loc)
(put-down board1 food-loc)
(pick-up bacon1 food-loc)
(move food-loc stove-loc)
(place-in bacon1 pan1 stove-loc)
; They place the bacon in a pan on the stove.
(cook grill pan1 stove1 stove-loc)
(pick-up pan1 stove-loc)
(move stove-loc plate-loc)
(transfer pan1 plate1 plate-loc)
; They grill the bacon on the stove, then transfer it to the plate.
(put-down pan1 plate-loc)
(move plate-loc food-loc)
(pick-up bread1 food-loc)
(move food-loc plate-loc)
(place-in bread1 plate1 plate-loc)
(move plate-loc food-loc)
(pick-up mayo1 food-loc)
(move food-loc plate-loc)
(place-in mayo1 plate1 plate-loc)
; They add bread and mayonnaise to the plate.
