(move start-loc food-loc)
(pick-up chicken1 food-loc)
(move food-loc fryer-loc)
(place-in chicken1 basket1 fryer-loc)
(cook deep-fry basket1 fryer1 fryer-loc)
; (cooked deep-fry chicken1)
(pick-up basket1 fryer-loc)
(move fryer-loc plate-loc)
(transfer basket1 plate1 plate-loc)
; (in-receptacle chicken1 plate1)
