(move start-loc food-loc)
(pick-up egg1 food-loc)
(move food-loc mix-loc)
(place-in egg1 mixing-bowl1 mix-loc)
(move mix-loc food-loc)
(pick-up flour1 food-loc)
(move food-loc mix-loc)
(place-in flour1 mixing-bowl1 mix-loc)
(combine mix mixing-bowl1 mixer1 mix-loc)
; (combined-with mix egg1 flour1)
(move mix-loc food-loc)
(pick-up ham1 food-loc)
(move food-loc chop-loc)
(place-in ham1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up tomato1 food-loc)
(move food-loc chop-loc)
(place-in tomato1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up pineapple1 food-loc)
(move food-loc chop-loc)
(place-in pineapple1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare chop board1 knife1 pineapple1 chop-loc)
(prepare slice board1 knife1 tomato1 chop-loc)
(prepare slice board1 knife1 ham1 chop-loc)
; (prepared slice tomato1) (prepared slice ham1) (prepared chop pineapple1)
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc tray-loc)
(transfer board1 tray1 tray-loc)
(move tray-loc food-loc)
(put-down board1 food-loc)
(pick-up cheese1 food-loc)
(move food-loc tray-loc)
(place-in cheese1 tray1 tray-loc)
(move tray-loc mix-loc)
(pick-up mixing-bowl1 mix-loc)
(move mix-loc tray-loc)
(transfer mixing-bowl1 tray1 tray-loc)
(put-down mixing-bowl1 tray-loc)
(pick-up tray1 tray-loc)
(move tray-loc oven-loc)
(put-down tray1 oven-loc)
(cook bake tray1 oven1 oven-loc)
; (cooked-with bake egg1 flour1) (cooked-with bake flour1 tomato1) (cooked-with bake tomato1 cheese1) (cooked-with bake cheese1 ham1) (cooked-with bake ham1 pineapple1)
(pick-up tray1 oven-loc)
(move oven-loc plate-loc)
(transfer tray1 plate1 plate-loc)
; (in-receptacle tomato1 plate1) (in-receptacle cheese1 plate1) (in-receptacle ham1 plate1) (in-receptacle pineapple1 plate1) (in-receptacle egg1 plate1) (in-receptacle flour1 plate1)
