(move start-loc food-loc)
(pick-up strawberry1 food-loc)
(move food-loc blend-loc)
(place-in strawberry1 blender-jug1 blend-loc)
(move blend-loc food-loc)
(pick-up milk1 food-loc)
(move food-loc blend-loc)
(place-in milk1 blender-jug1 blend-loc)
(combine blend blender-jug1 blender1 blend-loc)
; (combined-with blend strawberry1 milk1)
(pick-up blender-jug1 blend-loc)
(move blend-loc glass-loc)
(transfer blender-jug1 glass1 glass-loc)
; (in-receptacle strawberry1 glass1) (in-receptacle milk1 glass1)
