(move start-loc food-loc)
(pick-up feta-cheese1 food-loc)
(move food-loc chop-loc)
(place-in feta-cheese1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up tomato1 food-loc)
(move food-loc chop-loc)
(place-in tomato1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 tomato1 chop-loc)
(put-down knife1 chop-loc)
(pick-up glove1 chop-loc)
(prepare crumble board1 glove1 feta-cheese1 chop-loc)
; (prepared slice tomato1) (prepared crumble feta-cheese1)
(put-down glove1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc plate-loc)
(transfer board1 plate1 plate-loc)
; (in-receptacle tomato1 plate1) (in-receptacle feta-cheese1 plate1)
