;Full Bar
(define (problem cocktail-codex-problem-6-0)
    (:domain cocktail-codex)
    (:objects
    rum  bourbon vodka tequila mezcal sweet-vermouth dry-vermouth amaro scotch rye wine beer q-tonic ginger-beer tonic coke diet-coke sprite jarritos mexican-fanta mexican-coke lime-juice lemon-juice pineapple-juice cranberry-juice orange-juice sugar tajine salt simple-syrup demerra-syrup honey agave angostura-bitters pechauyds-bitters absinthe orange mint pineapple egg amarino-cherry olive crushed-ice sphere-ice collins-ice large-format-ice olive-juice grapefruit-juice cherry-juice pickle-juice vanilla nutmeg anise cinnamon toothpick cloves powdered-sugar dried-chili-pepper nori dried-orange-slice dried-lime-slice dried-lemon-slice dried-pineapple umbrella 
    - ftype ;Food types (remove duplicate tonic)
    shaker shaker-tin jigger cutting-board collins-glass rocks-glass coupe-glass martini-glass champagne-glass wine-glass tiki-glass shot-glass stirring-glass bar-mat canister bag - rtype ;Receptacle types
    blendernatype ;Appliance types
    stirrer bar-spoon hawthorne-strainer fine-mesh-strainer knife peeler swizzle-sticks tongs measuring-spoon zester juicer sous-vide-machine isi-whipper - ttype ;Tool types
    foam sous-vide cut pour strain double-strain dirty-dump rinse zest juice peel stir swizzzle - prepare-method ;Preparation methods 
    blend - combine-method ;Combine methods add dry-shake, whip-shake
    pour throw dirty-dump  shake pour-method;Pour methods 
    rum1  bourbon1 vodka1 tequila1 mezcal1 sweet-vermouth1 dry-vermouth1 amaro1 scotch1 rye1 wine1 beer1 q-tonic1 ginger-beer1 tonic1 coke1 diet-coke1 sprite1 jarritos1 mexican-fanta1 mexican-coke1 lime-juice1 lemon-juice1 pineapple-juice1 cranberry-juice1 orange-juice1 sugar1 tajine1 salt1 simple-syrup1 demerra-syrup1 honey1 agave1 angostura-bitters1 pechauyds-bitters1 absinthe1 orange1 mint1 pineapple1 egg1 amarino-cherry1 olive1 crushed-ice1 sphere-ice1 collins-ice1 large-format-ice1 olive-juice1 grapefruit-juice1 cherry-juice1 pickle-juice1 vanilla1 nutmeg1 anise1 cinnamon1 toothpick1 cloves1 powdered-sugar1 dried-chili-pepper1 nori1 dried-orange-slice1 dried-lime-slice1 dried-lemon-slice1 dried-pineapple1 umbrella1 - food 
   ;Food objects
    shaker1 shaker-tin1 jigger1 cutting-board1 collins-glass1 rocks-glass1 coupe-glass1 martini-glass1 champagne-glass1 wine-glass1 tiki-glass1 shot-glass1 stirring-glass1 bar-mat1 canister1 bag1 - receptacle ;Receptacle objects
    blender1 - appliance ;Appliance objects
    stirrer1 bar-spoon1 hawthorne-strainer1 fine-mesh-strainer1 knife1 peeler1 swizzle-sticks1 tongs1 measuring-spoon1 zester1 juicer1 sous-vide-machine1 isi-whipper1- tool ;Tool objects
    start-loc food-loc shaker-loc shaker-tin-loc jigger-loc canister-loc cutting-board-loc collins-glass-loc rocks-glass-loc coupe-glass-loc martini-glass-loc champagne-glass-loc wine-glass-loc tiki-glass-loc shot-glass-loc stirring-glass-loc blender-loc sous-vide-machine-loc isi-whipper-loc bar-mat-loc
   - location ; Locations
   )
 (:init
        ; Type declarations
        (food-type rum rum1)
        (food-type bourbon bourbon1)
        (food-type vodka vodka1)
        (food-type tequila tequila1)
        (food-type mezcal mezcal1)
        (food-type sweet-vermouth sweet-vermouth1)
        (food-type dry-vermouth dry-vermouth1)
        (food-type amaro amaro1)
        (food-type scotch scotch1)
        (food-type rye rye1)
        (food-type wine wine)
        (food-type beer beer1) 
        (food-type q-tonic q-tonic1) 
        (food-type ginger-beer ginger-beer1) 
        (food-type tonic tonic1) 
        (food-type coke coke1)    
        (food-type diet-coke diet-coke1) 
        (food-type sprite sprite1) 
        (food-type jarritos jarritos1)
        (food-type mexican-fanta mexican-fanta1)
        (food-type mexican-coke mexican-coke1) 
        (food-type lime-juice lime-juice1)
        (food-type lemon-juice lemon-juice1)
        (food-type pineapple-juice pineapple-juice1)
        (food-type cranberry-juice cranberry-juice1) 
        (food-type orange-juice orange-juice1) 
        (food-type sugar sugar1)
        (food-type tajine tajine1)
        (food-type salt salt1)
        (food-type simple-syrup simple-syrup1) 
        (food-type demerra-syrup demerra-syrup1) 
        (food-type honey honey1)
        (food-type agave agave1)
        (food-type angostura-bitters angostura-bitters1)
        (food-type pechauyds-bitters pechauyds-bitters1) 
        (food-type absinthe absinthe1)
        (food-type orange orange1) 
        (food-type mint mint1)
        (food-type pineapple pineapple1) 
        (food-type egg egg1) 
        (food-type amarino-cherry amarino-cherry1) 
        (food-type olive1 olive1) 
        (food-type crushed-ice crushed-ice1) 
        (food-type sphere-ice sphere-ice1) 
        (food-type collins-ice collins-ice1)
        (food-type large-format-ice large-format-ice1) 
        (food-type olive-juice olive-juice1) 
        (food-type grapefruit-juice grapefruit-juice1)
        (food-type cherry-juice cherry-juice1)
        (food-type pickle-juice pickle-juice1) 
        (food-type vanilla vanilla1)
        (food-type nutmeg nutmeg1) 
        (food-type anise anise1)
        (food-type cinnamon cinnamon1)
        (food-type toothpick toothpick1) 
        (food-type cloves clove1)
        (food-type powdered-sugar powdered-sugar1) 
        (food-type dried-chili-pepper dried-chili-pepper1) 
        (food-type nori nori1) 
        (food-type dried-orange-slice dried-orange-slice1) 
        (food-type dried-lime-slice dried-lime-slice1)
        (food-type dried-lemon-slice dried-lemon-slice1)
        (food-type dried-pineapple dried-pineapple1) 
        (food-type umbrella umbrella1)
        (receptacle-type shaker shaker1)
        (receptacle-type shaker-tin shaker-tin1)
        (receptacle-type jigger jigger1) 
        (receptacle-type cutting-board cutting-board1) 
        (receptacle-type collins-glass collins-glass1) 
        (receptacle-type rocks-glass rocks-glass1)
        (receptacle-type coupe-glass coupe-glass1) 
        (receptacle-type martini-glass martini-glass1) 
        (receptacle-type champagne-glass champagne-glass1) 
        (receptacle-type wine-glass wine-glass1)
        (receptacle-type tiki-glass tiki-glass1) 
        (receptacle-type shot-glass shot-glass1) 
        (receptacle-type stirring-glass stirring-glass1) 
        (receptacle-type bar-mat bar-mat1)
        (receptacle-type canister canister1)
        (receptacle-type bag bag1)
        (appliance-type blender blender1)
        (tool-type sous-vide-machine sous-vide-machine1) 
        (tool-type isi-whipper isi-whipper1)
        (tool-type stirrer stirrer1)
        (tool-type bar-spoon bar-spoon1)
        (tool-type hawthorne-strainer hawthorne-strainer1) 
        (tool-type fine-mesh-strainer fine-mesh-strainer1) 
        (tool-type knife knife1)
        (tool-type peeler peeler1)
        (tool-type swizzle-sticks swizzle-sticks1)
        (tool-type tongs tongs1) 
        (tool-type measuring-spoon measuring-spoon1)
        (tool-type zester zester1)
        (tool-type juicer juicer1) 
       ;Method declarations (change "glass" for each kind of glass)
        (has-prepare-method foam canister isi-whipper)
        (has-prepare-method sous-vide bag sous-vide-machine )
        (has-prepare-method cut cutting-board knife)
        (has-prepare-method pour shaker hawthorne-strainer)
        (has-prepare-method strain shaker fine-mesh-strainer)
        (has-prepare-method double-strain stirring-glass fine-mesh-strainer)
        (has-prepare-method rinse glass shot-glass)
        (has-prepare-method zest glass zester)
        (has-prepare-method peel cutting-board peeler)
        (has-prepare-method juice glass juicer)
        (has-prepare-method swizzle stirring-glass swizzle-sticks)
        (has-prepare-method stir stirring-glass bar-spoon)
        (has-pour-method pour shaker glass)
        (has-pour-method dirty-dump shaker glass)
        (has-pour-method throw shaker shaker-tin) 
        (has-pour-method shake shaker shaker-tin)   
        (has-combine-method blend blender-jug blender)
        ; Initial agent state
        (handempty)
        (agent-at-loc start-loc)
        ; Initial food locations
        (object-at-loc rum1 food-loc)
        (object-at-loc bourbon1 food-loc)
        (object-at-loc vodka1 food-loc)
        (object-at-loc tequila1 food-loc) 
        (object-at-loc mezcal1 food-loc)
        (object-at-loc sweet-vermouth1 food-loc)
        (object-at-loc dry-vermouth1 food-loc)
        (object-at-loc amaro1 food-loc)
        (object-at-loc scotch1 food-loc)
        (object-at-loc rye1 food-loc)
        (object-at-loc wine1 food-loc)
        (object-at-loc beer1 food-loc) 
        (object-at-loc ginger-beer1 food-loc) 
        (object-at-loc tonic1 food-loc) 
        (object-at-loc coke1 food-loc)    
        (object-at-loc diet-coke1 food-loc) 
        (object-at-loc sprite1 food-loc) 
        (object-at-loc jarritos1 food-loc)
        (object-at-loc mexican-fanta1 food-loc)
        (object-at-loc mexican-coke1 food-loc) 
        (object-at-loc lime-juice1 food-loc)
        (object-at-loc lemon-juice1 food-loc)
        (object-at-loc pineapple-juice1 food-loc)
        (object-at-loc cranberry-juice1 food-loc) 
        (object-at-loc orange-juice1 food-loc) 
        (object-at-loc sugar1 food-loc)
        (object-at-loc tajine1 food-loc)
        (object-at-loc salt1 food-loc)
        (object-at-loc simple-syrup1 food-loc) 
        (object-at-loc demerra-syrup1 food-loc) 
        (object-at-loc honey1 food-loc)
        (object-at-loc agave1 food-loc)
        (object-at-loc angostura-bitters1 food-loc)
        (object-at-loc pechauyds-bitters1 food-loc) 
        (object-at-loc absinthe1 food-loc)
        (object-at-loc orange1 food-loc) 
        (object-at-loc mint1 food-loc)
        (object-at-loc pineapple1 food-loc) 
        (object-at-loc egg1 food-loc) 
        (object-at-loc amarino-cherry1 food-loc) 
        (object-at-loc olive1 food-loc) 
        (object-at-loc crushed-ice1 food-loc) 
        (object-at-loc sphere-ice1) food-loc 
        (object-at-loc collins-ice1 food-loc)
        (object-at-loc large-format-ice1 food-loc) 
        (object-at-loc olive-juice1 food-loc) 
        (object-at-loc grapefruit-juice1 food-loc)
        (object-at-loc cherry-juice1 food-loc)
        (object-at-loc pickle-juice1 food-loc) 
        (object-at-loc vanilla1 food-loc)
        (object-at-loc nutmeg1 food-loc) 
        (object-at-loc anise1 food-loc)
        (object-at-loc cinnamon1 food-loc)
        (object-at-loc toothpick1 food-loc) 
        (object-at-loc clove1 food-loc)
        (object-at-loc powdered-sugar1 food-loc) 
        (object-at-loc dried-chili-pepper1 food-loc) 
        (object-at-loc nori1 food-loc) 
        (object-at-loc dried-orange-slice1 food-loc) 
        (object-at-loc dried-lime-slice1 food-loc)
        (object-at-loc dried-lemon-slice1 food-loc)
        (object-at-loc dried-pineapple1 food-loc) 
        (object-at-loc umbrella1 food-loc)
      ; Receptacle, tool, and appliance locations
        (object-at-loc shaker1 shaker-loc)
        (object-at-loc shaker-tin1 )shaker-tin-loc
        (object-at-loc jigger1 jigger-loc) 
        (object-at-loc cutting-board1 board-loc) 
        (object-at-loc collins-glass1 collins-glass-loc) 
        (object-at-loc rocks-glass1 rocks-glass-loc)
        (object-at-loc coupe-glass1 coupe-glass-loc) 
        (object-at-loc martini-glass1 martini-glass-loc) 
        (object-at-loc champagne-glass1 champagne-glass-loc) 
        (object-at-loc wine-glass1 wine-glass-loc)
        (object-at-loc tiki-glass1 wine-glass-loc ) 
        (object-at-loc shot-glass1 shot-glass-loc) 
        (object-at-loc stirring-glass1 stirring-glass-loc) 
        (object-at-loc bar-mat1 bar-mat-loc)
        (object-at-loc canister1 canister-loc)
        (object-at-loc bag1 bag-loc)
        (object-at-loc blender1 blender-loc)
        (object-at-loc sous-vide-machine1 sous-vide-machine-loc) 
        (object-at-loc isi-whipper1 isi-whipper-loc)
        (object-at-loc stirrer1 stirring-loc)
        (object-at-loc bar-spoon1 bar-spoon-loc)
        (object-at-loc hawthorne-strainer1 hawthorne-strainer-loc)
        (object-at-loc peeler1 peeler-loc)
        (object-at-loc swizzle-sticks1 swizzle-sticks-loc)
        (object-at-loc tongs1 tongs-loc) 
        (object-at-loc measuring-spoon1 measuring-spoon-loc)
        (object-at-loc zester1 zester-loc)
        (object-at-loc juicer1 juicer-loc) 
        ; Whether receptacles are located on appliances
        ;Goals 
       )      
      
       )
        
        