;Garden salad made of sliced lettuce, tomato, onion, and cucumber, topped with salad dressing and served in a plate.
        (exists (?lettuce - food ?tomato - food ?cucumber - food ?onion - food ?salad-dressing - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type cucumber ?cucumber)
                     (food-type onion ?onion)
                     (food-type salad-dressing ?salad-dressing)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (prepared slice ?cucumber)
                     (prepared slice ?onion)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?onion ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?salad-dressing ?plate)))
;A salad made of sliced tomato and cucumber and served in a plate.
        (exists (?cucumber - food ?tomato - food ?plate - receptacle)
                (and (food-type cucumber ?cucumber)
                     (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?cucumber)
                     (prepared slice ?tomato)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?tomato ?plate)))
;A salad made of sliced cucumber topped with salad dressing and served in a plate
        (exists (?cucumber - food ?salad-dressing - food ?plate - receptacle)
                (and (food-type cucumber ?cucumber)
                     (food-type salad-dressing ?salad-dressing)
                     (receptacle-type plate ?plate)
                     (prepared slice ?cucumber)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?salad-dressing ?plate)))
;A salad made of sliced lettuce, tomato, and cucumber, topped with a salad dressing and served in a plate.
        (exists (?lettuce - food ?tomato - food ?cucumber - food ?salad-dressing - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type cucumber ?cucumber)
                     (food-type salad-dressing ?salad-dressing)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tomato)
                     (prepared slice ?cucumber)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?salad-dressing ?plate)))
;A salad made of sliced onion, tomato, and lettuce and served in a plate. 
        (exists (?lettuce - food ?tomato - food ?onion - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type onion ?onion)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (prepared slice ?onion)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?onion ?plate)
                     (in-receptacle ?tomato ?plate)))
