; A salad made of sliced green leaf lettuce and freshly sliced tomato, served in a plate
        (exists (?lettuce - food ?tomato - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?tomato ?plate)))
; A salad made of sliced green leaf lettuce, freshly sliced tomato, and freshly sliced cucumber, served in a plate.
        (exists (?lettuce - food ?tomato - food ?cucumber - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type cucumber ?cucumber)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (prepared slice ?cucumber)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?tomato ?plate)))
; A salad made of sliced green leaf lettuce, served on a plate.
        (exists (?lettuce - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (in-receptacle ?lettuce ?plate)))
; A salad made of green leaf lettuce, freshly sliced tomato, and freshly sliced cucumber, served in a plate.
        (exists (?cucumber - food ?tomato - food ?plate - receptacle)
                (and (food-type cucumber ?cucumber)
                     (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?cucumber)
                     (prepared slice ?tomato)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?tomato ?plate)))
; A salad made of freshly sliced tomato, served on a plate.
        (exists (?tomato - food ?plate - receptacle)
                (and (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tomato)
                     (in-receptacle ?tomato ?plate)))