;A ham sandwich consisting of sliced ham and sliced cheese, layered with mayonnaise in bread.
        (exists (?ham - food ?bread - food ?cheese - food ?mayonnaise - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type ham ?ham)
                     (food-type cheese ?cheese)
                     (food-type mayonnaise ?mayonnaise)
                     (receptacle-type plate ?plate)
                     (prepared slice ?ham)
                     (prepared slice ?cheese)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?mayonnaise ?plate)
                     (in-receptacle ?cheese ?plate)))   
;A BLT consisting of grilled bacon, sliced lettuce, sliced tomato, with bread.
        (exists (?bread - food ?bacon - food ?lettuce - food ?tomato - food ?plate - receptacle)
                (and (food-type bacon ?bacon)
                     (food-type bread ?bread)
                     (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (cooked grill ?bacon)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?bacon ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?lettuce ?plate)))
;A sandwich consisting of sliced ham layered with mayonnaise in bread.
        (exists (?ham - food ?bread - food ?mayonnaise - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type ham ?ham)
                     (food-type mayonnaise ?mayonnaise)
                     (receptacle-type plate ?plate)
                     (prepared slice ?ham)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?mayonnaise ?plate)))
;A BLT consisting of grilled bacon, sliced lettuce, sliced tomato, layered with mayonnaise in bread
        (exists (?bread - food ?bacon - food ?lettuce - food ?tomato - food ?mayonnaise - food ?plate - receptacle)
                (and (food-type bacon ?bacon)
                     (food-type bread ?bread)
                     (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type mayonnaise ?mayonnaise)
                     (receptacle-type plate ?plate)
                     (cooked grill ?bacon)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?bacon ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?mayonnaise ?plate)
                     (in-receptacle ?lettuce ?plate)))
;A sandwich consisting of grilled bacon, sliced ham, sliced lettuce, slice tomato, sliced onion, layered with mayonnaise in bread.
        (exists (?bread - food ?bacon - food ?lettuce - food ?ham - food ?onion - food ?tomato - food ?mayonnaise - food ?plate - receptacle)
                (and (food-type bacon ?bacon)
                     (food-type bread ?bread)
                     (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type onion ?onion)
                     (food-type ham ?ham)
                     (food-type mayonnaise ?mayonnaise)
                     (receptacle-type plate ?plate)
                     (cooked grill ?bacon)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (prepared slice ?onion)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?onion ?plate)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?bacon ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?mayonnaise ?plate)
                     (in-receptacle ?lettuce ?plate)))