; A grilled cheese sandwich made of sliced cheese grilled with bread.
        (exists (?bread - food ?cheese - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type cheese ?cheese)
                     (receptacle-type plate ?plate)
                     (prepared slice ?cheese)
                     (cooked-with grill ?bread ?cheese)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?cheese ?plate)))
; A ham and cheese sandwich, made of sliced ham and cheese with bread.
        (exists (?ham - food ?bread - food ?cheese - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type ham ?ham)
                     (food-type cheese ?cheese)
                     (receptacle-type plate ?plate)
                     (prepared slice ?ham)
                     (prepared slice ?cheese)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?cheese ?plate)))
; A ham, cheese, and veggie sandwich, made of sliced ham, cheese, lettuce, and tomato with bread.
        (exists (?ham - food ?bread - food ?cheese - food ?lettuce - food ?tomato - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type ham ?ham)
                     (food-type cheese ?cheese)
                     (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?ham)
                     (prepared slice ?cheese)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?cheese ?plate)))
; A ham, cheese, and veggie sandwich with onion, made of sliced ham, cheese, lettuce, tomato, and onion with bread.
        (exists (?ham - food ?bread - food ?cheese - food ?lettuce - food ?tomato - food ?onion - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type ham ?ham)
                     (food-type cheese ?cheese)
                     (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type onion ?onion)
                     (receptacle-type plate ?plate)
                     (prepared slice ?ham)
                     (prepared slice ?cheese)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (prepared slice ?onion)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?onion ?plate)
                     (in-receptacle ?cheese ?plate)))
; A grilled ham and cheese sandwich made of sliced ham and cheese grilled with bread.
        (exists (?ham - food ?bread - food ?cheese - food ?plate - receptacle)
                (and (food-type bread ?bread)
                     (food-type ham ?ham)
                     (food-type cheese ?cheese)
                     (receptacle-type plate ?plate)
                     (prepared slice ?ham)
                     (prepared slice ?cheese)
                     (cooked-with grill ?bread ?cheese)
                     (cooked-with grill ?ham ?cheese)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?bread ?plate)
                     (in-receptacle ?cheese ?plate)))