;Goal 1: Sliced tomato and lettuce
        (exists (?lettuce - food ?tomato - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?tomato ?plate)))
; Goal 2: Sliced tomato, lettuce, and cucumber
        (exists (?lettuce - food ?tomato - food ?cucumber - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (food-type tomato ?tomato)
                     (food-type cucumber ?cucumber)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (prepared slice ?tomato)
                     (prepared slice ?cucumber)
                     (in-receptacle ?lettuce ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?tomato ?plate)))
; Goal 3: Sliced lettuce
        (exists (?lettuce - food ?plate - receptacle)
                (and (food-type lettuce ?lettuce)
                     (receptacle-type plate ?plate)
                     (prepared slice ?lettuce)
                     (in-receptacle ?lettuce ?plate)))
; Goal 4: Sliced tomato and cucumber
        (exists (?cucumber - food ?tomato - food ?plate - receptacle)
                (and (food-type cucumber ?cucumber)
                     (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?cucumber)
                     (prepared slice ?tomato)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?tomato ?plate)))
; Goal 5: Sliced tomato
        (exists (?tomato - food ?plate - receptacle)
                (and (food-type tomato ?tomato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tomato)
                     (in-receptacle ?tomato ?plate)))