;A piece of nigiri made of boiled rice topped with raw sliced salmon.
    (exists (?nori - food ?rice - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?salmon ?plate)))
    
;A tuna roll made of sliced raw tuna, boiled rice, and nori.
        (exists (?nori - food ?rice - food ?tuna - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)))

;A tuna and salmon roll made of sliced raw tuna, salmon, boiled rice, and nori.
        (exists (?nori - food ?rice - food ?salmon - food ?tuna - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)
                     (in-receptacle ?salmon ?plate)))
;Tuna nigiri made of raw sliced tuna and boiled rice.
        (exists (?rice - food ?tuna - food ?plate - receptacle)
                (and (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (cooked boil ?rice)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)))
;Salmon nigiri made of raw sliced salmon and boiled rice.
        (exists (?rice - food ?salmon - food ?plate - receptacle)
                (and (food-type rice ?rice)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?salmon ?plate)))