; A freshly baked chocolate cake made from chocolate, egg and flour batter.
        (exists (?egg - food ?chocolate - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type chocolate ?chocolate)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?egg ?flour)
                     (combined-with mix ?flour ?chocolate)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?chocolate)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?chocolate ?plate)
                     (in-receptacle ?flour ?plate)))
; A freshly baked strawberry cake made from strawberry, egg and flour batter.
        (exists (?egg - food ?strawberry - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type strawberry ?strawberry)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?egg ?flour)
                     (combined-with mix ?flour ?strawberry)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?strawberry)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?strawberry ?plate)
                     (in-receptacle ?flour ?plate)))
; A freshly baked apple pie made from apple baked with dough made from egg and flour.
        (exists (?egg - food ?apple - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type apple ?apple)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?egg ?flour)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?apple)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?apple ?plate)
                     (in-receptacle ?flour ?plate)))
; A freshly baked strawberry chocolate cake made from chocolate, strawberry, egg and flour batter.
        (exists (?egg - food ?chocolate - food ?strawberry - food ?flour - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type chocolate ?chocolate)
                     (food-type strawberry ?strawberry)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?egg ?flour)
                     (combined-with mix ?flour ?strawberry)
                     (combined-with mix ?strawberry ?chocolate)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?strawberry)
                     (cooked-with bake ?strawberry ?chocolate)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?strawberry ?plate)
                     (in-receptacle ?chocolate ?plate)
                     (in-receptacle ?flour ?plate)))
; A plate of chocolate-coated strawberries, made by mixing strawberries with chocolate.
        (exists (?chocolate - food ?strawberry - food ?plate - receptacle)
                (and (food-type chocolate ?chocolate)
                     (food-type strawberry ?strawberry)
                     (receptacle-type plate ?plate)
                     (combined-with mix ?chocolate ?strawberry)
                     (in-receptacle ?chocolate ?plate)
                     (in-receptacle ?strawberry ?plate)))