; Goal 1: Chocolate milkshake
        (exists (?ice - food ?chocolate - food ?milk - food ?glass - receptacle)
                (and (food-type ice ?ice)
                     (food-type milk ?milk)
                     (food-type chocolate ?chocolate)
                     (receptacle-type glass ?glass)
                     (combined-with blend ?ice ?milk)
                     (combined-with blend ?milk ?chocolate)
                     (in-receptacle ?ice ?glass)
                     (in-receptacle ?chocolate ?glass)
                     (in-receptacle ?milk ?glass)))
; Goal 2: Chocolate milk
        (exists (?chocolate - food ?milk - food ?glass - receptacle)
                (and (food-type milk ?milk)
                     (food-type chocolate ?chocolate)
                     (receptacle-type glass ?glass)
                     (combined-with blend ?milk ?chocolate)
                     (in-receptacle ?chocolate ?glass)
                     (in-receptacle ?milk ?glass)))
; Goal 3: Strawberry milk
        (exists (?strawberry - food ?milk - food ?glass - receptacle)
                (and (food-type milk ?milk)
                     (food-type strawberry ?strawberry)
                     (receptacle-type glass ?glass)
                     (combined-with blend ?strawberry ?milk)
                     (in-receptacle ?strawberry ?glass)
                     (in-receptacle ?milk ?glass)))
; Goal 4: Watermelon, apple, grape smoothie
        (exists (?ice - food ?watermelon - food ?apple - food ?grape - food ?glass - receptacle)
                (and (food-type ice ?ice)
                     (food-type watermelon ?watermelon)
                     (food-type apple ?apple)
                     (food-type grape ?grape)
                     (receptacle-type glass ?glass)
                     (combined-with blend ?grape ?watermelon)
                     (combined-with blend ?watermelon ?apple)
                     (combined-with blend ?apple ?ice)
                     (in-receptacle ?apple ?glass)
                     (in-receptacle ?watermelon ?glass)
                     (in-receptacle ?grape ?glass)
                     (in-receptacle ?ice ?glass)))
; Goal 5: Watermelon, apple. strawberry smoothie
        (exists (?ice - food ?watermelon - food ?apple - food ?strawberry - food ?glass - receptacle)
                (and (food-type ice ?ice)
                     (food-type watermelon ?watermelon)
                     (food-type apple ?apple)
                     (food-type strawberry ?strawberry)
                     (receptacle-type glass ?glass)
                     (combined-with blend ?strawberry ?watermelon)
                     (combined-with blend ?watermelon ?apple)
                     (combined-with blend ?apple ?ice)
                     (in-receptacle ?apple ?glass)
                     (in-receptacle ?watermelon ?glass)
                     (in-receptacle ?strawberry ?glass)
                     (in-receptacle ?ice ?glass)))