;A rolled maki sushi roll filled with tuna, nori and rice, served in a plate.
        (exists (?nori - food ?rice - food ?tuna - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)))
;A rolled maki sushi roll filled with tuna, cucumber, nori and rice, served in a plate.
        (exists (?nori - food ?rice - food ?tuna - food ?cucumber - food  ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (food-type cucumber ?cucumber)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (prepared slice ?cucumber)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?tuna ?plate)))
;A rolled maki sushi roll filled with salmon, cucumber, nori and rice, served in a plate.
        (exists (?nori - food ?rice - food ?cucumber - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type cucumber ?cucumber)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?salmon)
                     (prepared slice ?cucumber)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?salmon ?plate)))
;A rolled maki sushi roll filled with cucumber, nori and rice, served in a plate.
        (exists (?nori - food ?rice - food ?cucumber - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type cucumber ?cucumber)
                     (receptacle-type plate ?plate)
                     (prepared slice ?cucumber)
                     (cooked boil ?rice)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?cucumber ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?cucumber ?plate)))
;A rolled maki sushi roll filled with tuna, salmon, nori and rice, served in a plate.
        (exists (?nori - food ?rice - food ?tuna - food ?salmon - food ?plate - receptacle)
                (and (food-type nori ?nori)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (food-type salmon ?salmon)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?salmon ?plate)
                     (in-receptacle ?nori ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)))