;A classic cheeseburger made of grilled beef, sliced cheese, and a fresh hamburger bun, served with a side of fries on a plate.
        (exists (?hamburger-bun - food ?beef - food ?cheese - food ?potato - food ?plate - receptacle)
                (and (food-type beef ?beef)
                     (food-type hamburger-bun ?hamburger-bun)
                     (food-type cheese ?cheese)
                     (food-type potato ?potato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?cheese)
                     (prepared slice ?potato)
                     (cooked grill ?beef)
                     (cooked deep-fry ?potato)
                     (in-receptacle ?hamburger-bun ?plate)
                     (in-receptacle ?beef ?plate)
                     (in-receptacle ?cheese ?plate)
                     (in-receptacle ?potato ?plate)))
;A classic cheeseburger made of grilled beef, sliced cheese, and a fresh hamburger bun, served on a plate.
        (exists (?hamburger-bun - food ?beef - food ?cheese - food ?plate - receptacle)
                (and (food-type beef ?beef)
                     (food-type hamburger-bun ?hamburger-bun)
                     (food-type cheese ?cheese)
                     (receptacle-type plate ?plate)
                     (cooked grill ?beef)
                     (prepared slice ?cheese)
                     (in-receptacle ?hamburger-bun ?plate)
                     (in-receptacle ?beef ?plate)
                     (in-receptacle ?cheese ?plate)))
;A classic hamburger made of grilled beef, sliced onion, and a fresh hamburger bun, served on a plate.
        (exists (?hamburger-bun - food ?beef - food ?onion - food ?potato - food ?plate - receptacle)
                (and (food-type beef ?beef)
                     (food-type onion ?onion)
                     (food-type hamburger-bun ?hamburger-bun)
                     (receptacle-type plate ?plate)
                     (prepared slice ?onion)
                     (cooked grill ?onion)
                     (cooked grill ?beef)
                     (in-receptacle ?hamburger-bun ?plate)
                     (in-receptacle ?onion ?plate)
                     (in-receptacle ?beef ?plate)))
;A classic hamburger made of grilled beef and a fresh hamburger bun, served with a side of fries on a plate.
        (exists (?hamburger-bun - food ?beef - food ?potato - food ?plate - receptacle)
                (and (food-type beef ?beef)
                     (food-type hamburger-bun ?hamburger-bun)
                     (food-type potato ?potato)
                     (receptacle-type plate ?plate)
                     (cooked grill ?beef)
                     (prepared slice ?potato)
                     (cooked deep-fry ?potato)
                     (in-receptacle ?hamburger-bun ?plate)
                     (in-receptacle ?beef ?plate)
                     (in-receptacle ?potato ?plate)))
;A side of fries on a plate.
        (exists (?potato - food ?plate - receptacle)
                (and (food-type potato ?potato)
                     (receptacle-type plate ?plate)
                     (prepared slice ?potato)
                     (cooked deep-fry ?potato)
                     (in-receptacle ?potato ?plate)))