;Tuna nigiri made from raw sliced tuna on top of boiled sushi rice.
        (exists (?tuna - food ?rice - food ?plate - receptacle)
                (and (food-type tuna ?tuna)
                     (food-type rice ?rice)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tuna)
                     (cooked boil ?rice)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)))
;Salmon nigiri made from raw sliced salmon on top of boiled sushi rice, served on a plate.
        (exists (?salmon - food ?rice - food ?plate - receptacle)
                (and (food-type salmon ?salmon)
                     (food-type rice ?rice)
                     (receptacle-type plate ?plate)
                     (prepared slice ?salmon)
                     (cooked boil ?rice)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?salmon ?plate)))
;Tuna and salmon nigiri made from raw sliced tuna and salmon on top of boiled sushi rice, served on a plate.
        (exists (?salmon - food ?rice - food ?tuna - food ?plate - receptacle)
                (and (food-type salmon ?salmon)
                     (food-type rice ?rice)
                     (food-type tuna ?tuna)
                     (receptacle-type plate ?plate)
                     (prepared slice ?salmon)
                     (prepared slice ?tuna)
                     (cooked boil ?rice)
                     (in-receptacle ?salmon ?plate)
                     (in-receptacle ?rice ?plate)
                     (in-receptacle ?tuna ?plate)))
;Grilled tuna on top of boiled white rice, served in a bowl.
        (exists (?tuna - food ?rice - food ?bowl - receptacle)
                (and (food-type tuna ?tuna)
                     (food-type rice ?rice)
                     (receptacle-type bowl ?bowl)
                     (prepared slice ?tuna)
                     (cooked grill ?tuna)
                     (cooked boil ?rice)
                     (in-receptacle ?rice ?bowl)
                     (in-receptacle ?tuna ?bowl)))
;Tuna sashimi on top of boiled white rice, served in a bowl.
        (exists (?tuna - food ?rice - food ?bowl - receptacle)
                (and (food-type tuna ?tuna)
                     (food-type rice ?rice)
                     (receptacle-type bowl ?bowl)
                     (prepared slice ?tuna)
                     (cooked boil ?rice)
                     (in-receptacle ?rice ?bowl)
                     (in-receptacle ?tuna ?bowl)))