; Hawaiian style pizza made with mozarella cheese, tomato sauce, ham, and pineapple, baked on pizza dough made from egg and flour.
        (exists (?egg - food ?flour - food ?tomato - food ?cheese - food ?ham - food ?pineapple - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type tomato ?tomato)
                     (food-type cheese ?cheese)
                     (food-type ham ?ham)
                     (food-type pineapple ?pineapple)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tomato)
                     (prepared slice ?ham)
                     (prepared chop ?pineapple)
                     (combined-with mix ?egg ?flour)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?tomato)
                     (cooked-with bake ?tomato ?cheese)
                     (cooked-with bake ?cheese ?ham)
                     (cooked-with bake ?ham ?pineapple)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?cheese ?plate)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?pineapple ?plate)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?flour ?plate)))
; A meatlover's pizza made with mozarella cheese, tomato sauce, ham, beef, and sausage baked on pizza dough made from egg and flour.
        (exists (?egg - food ?flour - food ?tomato - food ?cheese - food ?sausage - food ?beef - food ?ham - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type tomato ?tomato)
                     (food-type cheese ?cheese)
                     (food-type sausage ?sausage)
                     (food-type beef ?beef)
                     (food-type ham ?ham)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tomato)
                     (prepared slice ?sausage)
                     (prepared slice ?ham)
                     (prepared chop ?beef)
                     (combined-with mix ?egg ?flour)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?tomato)
                     (cooked-with bake ?tomato ?cheese)
                     (cooked-with bake ?cheese ?sausage)
                     (cooked-with bake ?sausage ?beef)
                     (cooked-with bake ?beef ?ham)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?cheese ?plate)
                     (in-receptacle ?beef ?plate)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?sausage ?plate)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?flour ?plate)))
; A ham pizza made with mozarella cheese, tomato sauce and ham, baked on pizza dough made from egg and flour.
        (exists (?egg - food ?flour - food ?tomato - food ?cheese - food ?ham - food ?plate - receptacle)
                (and (food-type egg ?egg)
                     (food-type flour ?flour)
                     (food-type tomato ?tomato)
                     (food-type cheese ?cheese)
                     (food-type ham ?ham)
                     (receptacle-type plate ?plate)
                     (prepared slice ?tomato)
                     (prepared slice ?ham)
                     (combined-with mix ?egg ?flour)
                     (cooked-with bake ?egg ?flour)
                     (cooked-with bake ?flour ?tomato)
                     (cooked-with bake ?tomato ?cheese)
                     (cooked-with bake ?cheese ?ham)
                     (in-receptacle ?tomato ?plate)
                     (in-receptacle ?cheese ?plate)
                     (in-receptacle ?ham ?plate)
                     (in-receptacle ?egg ?plate)
                     (in-receptacle ?flour ?plate)))
; A pepperoni pizza made with mozarella cheese, tomato sauce, and sausage baked on pizza dough made from egg and flour.
        (exists (?egg - food ?flour - food ?tomato - food ?cheese - food ?sausage - food ?plate - receptacle)
            (and (food-type egg ?egg)
                 (food-type flour ?flour)
                 (food-type tomato ?tomato)
                 (food-type cheese ?cheese)
                 (food-type sausage ?sausage)
                 (receptacle-type plate ?plate)
                 (prepared slice ?tomato)
                 (prepared slice ?sausage)
                 (combined-with mix ?egg ?flour)
                 (cooked-with bake ?egg ?flour)
                 (cooked-with bake ?tomato ?flour)
                 (cooked-with bake ?tomato ?cheese)
                 (cooked-with bake ?cheese ?sausage)
                 (in-receptacle ?tomato ?plate)
                 (in-receptacle ?cheese ?plate)
                 (in-receptacle ?sausage ?plate)
                 (in-receptacle ?egg ?plate)
                 (in-receptacle ?flour ?plate)))
; A cheese pizza made with mozarella cheese and tomato sauce, baked on pizza dough made from egg and flour.
        (exists (?egg - food ?flour - food ?tomato - food ?cheese - food ?plate - receptacle)
            (and (food-type egg ?egg)
                 (food-type flour ?flour)
                 (food-type tomato ?tomato)
                 (food-type cheese ?cheese)
                 (receptacle-type plate ?plate)
                 (prepared slice ?tomato)
                 (combined-with mix ?egg ?flour)
                 (cooked-with bake ?egg ?flour)
                 (cooked-with bake ?tomato ?flour)
                 (cooked-with bake ?tomato ?cheese)
                 (in-receptacle ?tomato ?plate)
                 (in-receptacle ?cheese ?plate)
                 (in-receptacle ?egg ?plate)
                 (in-receptacle ?flour ?plate)))