(define (domain continuum-2d)
    (:requirements :fluents :adl :typing)
    (:types area)
    (:predicates (wall ?x1 ?y1 ?x2 ?y2)
                 (extent ?a - area ?x1 ?y1 ?x2 ?y2)
                 (in_area ?a ?x ?y))
    (:functions (xpos) (ypos) (width) (height))
    (:derived (in_area ?a ?x ?y)
              (and (extent ?a ?x1 ?y1 ?x2 ?y2)
                   (>= ?x ?x1) (<= ?x ?x2)
                   (>= ?y ?y1) (<= ?y ?y2)))
    (:action move
     :parameters (?x ?y)
     :precondition (not (and (wall ?x1 ?y1 ?x2 ?y2)
                             (>= ?x ?x1) (<= ?x ?x2)
                             (>= ?y ?y1) (<= ?y ?y2)
                             (>= ?x 0) (<= ?x width)
                             (>= ?y 0) (<= ?y height)))
     :effect (and (assign xpos ?x) (assign ypos ?y))
    )
)
