(move start-loc food-loc)
(pick-up beef1 food-loc)
(move food-loc stove-loc)
(place-in beef1 pan1 stove-loc)
(cook grill pan1 stove1 stove-loc)
; (cooked grill beef1)
(pick-up pan1 stove-loc)
(move stove-loc plate-loc)
(transfer pan1 plate1 plate-loc)
; (in-receptacle beef1 plate1)
(move plate-loc stove-loc)
(put-down pan1 stove-loc)
(move stove-loc food-loc)
(pick-up onion1 food-loc)
(move food-loc chop-loc)
(place-in onion1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 onion1 chop-loc)
; (prepared slice onion1)
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc stove-loc)
(transfer board1 pan1 stove-loc)
(cook grill pan1 stove1 stove-loc)
; (cooked grill onion1)
(move stove-loc plate-loc)
(put-down board1 plate-loc)
(move plate-loc stove-loc)
(pick-up pan1 stove-loc)
(move stove-loc plate-loc)
(transfer pan1 plate1 plate-loc)
; (in-receptacle onion1 plate1)
(put-down pan1 plate-loc)
(move plate-loc food-loc)
(pick-up hamburger-bun1 food-loc)
(move food-loc plate-loc)
(place-in hamburger-bun1 plate1 plate-loc)
; (in-receptacle hamburger-bun1 plate1)
