(move start-loc food-loc)
(pick-up lettuce1 food-loc)
(move food-loc chop-loc)
(place-in lettuce1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up tomato1 food-loc)
(move food-loc chop-loc)
(place-in tomato1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 tomato1 chop-loc)
(prepare slice board1 knife1 lettuce1 chop-loc)
; (prepared slice lettuce1) (prepared slice tomato1)
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc plate-loc)
(transfer board1 plate1 plate-loc)
; (in-receptacle lettuce1 plate1) (in-receptacle tomato1 plate1)
(move plate-loc food-loc)
(put-down board1 food-loc)
(pick-up bacon1 food-loc)
(move food-loc stove-loc)
(place-in bacon1 pan1 stove-loc)
(cook grill pan1 stove1 stove-loc)
; (cooked grill bacon1)
(pick-up pan1 stove-loc)
(move stove-loc plate-loc)
(transfer pan1 plate1 plate-loc)
; (in-receptacle bacon1 plate1)
(put-down pan1 plate-loc)
(move plate-loc food-loc)
(pick-up bread1 food-loc)
(move food-loc plate-loc)
(place-in bread1 plate1 plate-loc)
(move plate-loc food-loc)
(pick-up mayo1 food-loc)
(move food-loc plate-loc)
(place-in mayo1 plate1 plate-loc)
; (in-receptacle bread1 plate1) (in-receptacle mayo1 plate1)
