(move start-loc food-loc)
(pick-up lettuce1 food-loc)
(move food-loc chop-loc)
(place-in lettuce1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up cheese1 food-loc)
(move food-loc chop-loc)
(place-in cheese1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up tomato1 food-loc)
(move food-loc chop-loc)
(place-in tomato1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 tomato1 chop-loc)
(prepare slice board1 knife1 cheese1 chop-loc)
(prepare slice board1 knife1 lettuce1 chop-loc)
; (prepared slice cheese1) (prepared slice tomato1) (prepared slice lettuce1)
(put-down knife1 chop-loc)
(pick-up board1 chop-loc)
(move chop-loc plate-loc)
(transfer board1 plate1 plate-loc)
; (in-receptacle cheese1 plate1) (in-receptacle tomato1 plate1) (in-receptacle lettuce1 plate1)
(move plate-loc food-loc)
(put-down board1 food-loc)
(pick-up chicken1 food-loc)
(move food-loc stove-loc)
(place-in chicken1 pan1 stove-loc)
(cook grill pan1 stove1 stove-loc)
; (cooked grill chicken1)
(pick-up pan1 stove-loc)
(move stove-loc plate-loc)
(transfer pan1 plate1 plate-loc)
; (in-receptacle chicken1 plate1)
(move plate-loc food-loc)
(put-down pan1 food-loc)
(pick-up bread1 food-loc)
(move food-loc plate-loc)
(place-in bread1 plate1 plate-loc)
; (in-receptacle bread1 plate1)
