(move start-loc food-loc)
(pick-up cheese1 food-loc)
(move food-loc chop-loc)
(place-in cheese1 board1 chop-loc)
(move chop-loc food-loc)
(pick-up potato1 food-loc)
(move food-loc chop-loc)
(place-in potato1 board1 chop-loc)
(pick-up knife1 chop-loc)
(prepare slice board1 knife1 potato1 chop-loc)
(prepare slice board1 knife1 cheese1 chop-loc)
; (prepared slice cheese1) (prepared slice potato1)
(move chop-loc food-loc)
(put-down knife1 food-loc)
(pick-up tuna1 food-loc)
(move food-loc mix-loc)
(place-in tuna1 mixing-bowl1 mix-loc)
(move mix-loc food-loc)
(pick-up mayo1 food-loc)
(move food-loc mix-loc)
(place-in mayo1 mixing-bowl1 mix-loc)
(combine mix mixing-bowl1 mixer1 mix-loc)
; (combined-with mix tuna1 mayo1)
(pick-up mixing-bowl1 mix-loc)
(move mix-loc stove-loc)
(transfer mixing-bowl1 pan1 stove-loc)
(move stove-loc chop-loc)
(put-down mixing-bowl1 chop-loc)
(take-out potato1 board1 chop-loc)
(move chop-loc fryer-loc)
(place-in potato1 basket1 fryer-loc)
(cook deep-fry basket1 fryer1 fryer-loc)
(move fryer-loc food-loc)
(pick-up bread1 food-loc)
(move food-loc stove-loc)
(place-in bread1 pan1 stove-loc)
(move stove-loc chop-loc)
(pick-up board1 chop-loc)
(move chop-loc stove-loc)
(transfer board1 pan1 stove-loc)
(cook grill pan1 stove1 stove-loc)
; (cooked deep-fry potato1) (cooked-with grill bread1 cheese1) (cooked-with grill tuna1 cheese1)
(move stove-loc chop-loc)
(put-down board1 chop-loc)
(move chop-loc stove-loc)
(pick-up pan1 stove-loc)
(move stove-loc plate-loc)
(transfer pan1 plate1 plate-loc)
(move plate-loc chop-loc)
(put-down pan1 chop-loc)
(move chop-loc fryer-loc)
(pick-up basket1 fryer-loc)
(move fryer-loc plate-loc)
(transfer basket1 plate1 plate-loc)
; (in-receptacle bread1 plate1) (in-receptacle tuna1 plate1) (in-receptacle mayo1 plate1) (in-receptacle cheese1 plate1) (in-receptacle potato1 plate1)
